### ISSUE TITLE
Package 'ansi-color' not found

### ISSUE THREAD

**Issue by ho-ho-ho** [martynsmith/node-irc#389]
Yesterday, i had no problems installing the irc package from npm, but today I got this error:
```
npm ERR! failed to fetch from registry: https://registry.npmjs.org/ansi-color
```

It seems like the ansi-color package was deleted or something like that ( https://www.npmjs.com/package/ansi-color ).
Browsing the irc code, I didn't see a mention of ansi-color in the production code, only in tests. Maybe moving ansi-color to devDependencies would fix the issue for the moment ( as installing with --production would not try to install it anymore ). In the long term, a replacement has to be found, I guess.

Greetings,
ho-ho-ho

**Comment by Jnull** [comment]
I'm not getting this error, i believe you were having another issue with npm itself. 

It just worked for me: 
C:\Users\Void\tips>npm install -g ansi-color
ansi-color@0.2.1 C:\Users\Void\AppData\Roaming\npm\node_modules\ansi-color

Recommend this be closed.

**Comment by ho-ho-ho** [comment]
Just tested it again and ... it works ! The only thing I did in the meantime was updating npm ( and node to 4.0 ).
Seems like the package is still there. But I would still recommend moving it from `dependencies` to `devDependencies` as it is only used in the tests.

Thanks Jnull

**Comment by Jnull** [comment]
np - I would make the suggestion about moving the dependency to dev side of package.json to the contributors, but there are a lot of pressing issues just getting the repo back to a more functional and stable state..   

If you know how to fork the project and contribute, i would recommend you do a pull request. Since its such a minor change, it might not matter and get pulled in. 

We just need people willing to help contribute / answer questions.

**Comment by ho-ho-ho** [comment]
Just created a PR for it: https://github.com/martynsmith/node-irc/pull/407

**Comment by Jnull** [comment]
Awesome!
