### ISSUE TITLE
 Microsoft Visual Studio needed to install this in windoze

### ISSUE THREAD

**Issue by teknopaul** [martynsmith/node-irc#390]
Hi,

any chance there could be an option for a version that does not require native code.

I can't build this in Windows 7 because building ansi-color fails in windows.

I don't plan to have any output, of any colour to the console.

**Comment by Jnull** [comment]
I believe you missed this note on the main repo page: 

Note that as of version 0.3.8, node-irc supports character set detection using icu. You'll need to install libiconv (if necessary; Linux systems tend to ship this in their glibc) and libicu (and its headers, if necessary) in order to use this feature. If you do not have these libraries or their headers installed, you will receive errors when trying to build these dependencies. However, node-irc will still install (assuming nothing else failed) and you'll be able to use it, just not the character set features.

node-irc should still work, even without those dependencies.

**Comment by moshmage** [comment]
@Jnull then.. solved?

**Comment by teknopaul** [comment]
I guess if everyone just installed Micro$oft's proprietary tool chain instead of gcc these horrible error would messages go away  :)

**Comment by Jnull** [comment]
No response, please move to close.
