### ISSUE TITLE
disconnect does not appear to send the reason to the server

### ISSUE THREAD

**Issue by ericblade** [martynsmith/node-irc#89]
Calling disconnect("user pressed disconnect button") gives me a quit message of "Client Quit".  Either it's not sending the message with the QUIT command, or it's just flat disconnecting before sending..

**Comment by ward** [comment]
I believe this was fixed by commit https://github.com/martynsmith/node-irc/commit/574f2b0a730e558eb23447af5ea374ed4e629b91

You can follow the trail via PR https://github.com/martynsmith/node-irc/pull/100 which was closed for bug https://github.com/martynsmith/node-irc/issues/138 which was closed by said commit.
